name: Autopublisher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publishing_job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Git to Staging Repo
        run: |
          $GITHUB_WORKSPACE/publisher/auto_git2staging.sh
      - name: Staging to Prod Repo
        run: |
          $GITHUB_WORKSPACE/publisher/auto_staging2prod.sh
      - name: Cleanup Staging Repo
        run: |
          $GITHUB_WORKSPACE/publisher/auto_stagingcleanup.sh

